### ISSUE TITLE
mincblur -3dfwhm dimension order mismatch

### ISSUE THREAD

**Issue by mcvaneede** [BIC-MNI/mni_autoreg#11]
I was trying to apply a 3D Gaussian blurring kernel to a 2D slice:

```
mincinfo 2D_slice.mnc 
file: 2D_slice.mnc
image: unsigned short 0 to 65535
image dimensions: zspace xspace yspace
    dimension name         length         step        start
    --------------         ------         ----        -----
    zspace                      1         0.38        -0.38
    xspace                    192    -0.260417      24.8698
    yspace                    200        -0.25       24.875
```

Reading the manual page for mincblur, it seems like it wants the size of the kernel in x,y,z order (not dimension order), however the following command:

```
mincblur  -3dfwhm 5.0 5.0 0.0001 2D_slice.mnc 2D_slice_5mm_xy
Making byte volume...
```

Upon visual inspection does not actually blur in the x-dimension. So I tried to feed the arguments in dimension order, but got:

```
mincblur  -3dfwhm 0.0001 5.0 5.0  2D_slice.mnc 2D_slice_5mm_xy
Error in mincblur in file /projects/mice/share/arch/linux-3_2_0-36-generic-x86_64-eglibc-2_15/src/minc-toolkit/mni_autoreg/mincblur/apodize_data.c, line 91
FWHM is greater than slice dimension
```

I then made the slice artificially thick and tried the last command again. This correctly blurred the file in x and y. It looks like mincblur determines whether the blur can be applied based on the x,y,z input, but applies it to the dimension order that the file is stored in:

```
minc_modify_header -dinsert zspace:step=10 2D_slice.mnc
mincblur  -3dfwhm 0.0001  5.0 5.0  2D_slice.mnc 2D_slice_5mm_xy
Making byte volume...
```

**Comment by vfonov** [comment]
@rdvincent can you take a look at this?

**Comment by rdvincent** [comment]
@mcvaneede Can you check the version of mincblur where this is occurring? I think this may have been at least partially fixed in recent versions.

**Comment by mcvaneede** [comment]
$ mincblur  -version
The program <mincblur> was built from:
mni_autoreg 0.99.60

This is the version that came with minc-toolkit release-1.0.02

**Comment by rdvincent** [comment]
That's what I figured. Your version probably has the "-xslice" option, which was removed when this issue was addressed a while back.

**Comment by mcvaneede** [comment]
Correct!
