### ISSUE TITLE
mutual information and thresholds

### ISSUE THREAD

**Issue by andrewjanke** [BIC-MNI/mni_autoreg#8]
Another from the mailing list. I don't see a pull request for this so not sure if it ever happened.

---

I believe I've found a bug in minctracc. The -threshold option allows you to set thresholds, which are supposed to be specified in terms of the real range. However, when using the mutual information objective function (-mi) the input volumes are automatically converted to bytes, and the thresholds get interpreted in the range 0-255.

The culprit seems to be the function that is used to convert the data, namely replace_volume_data_with_ubyte() in minctracc/Optimize/optimize.c, which contains the following comment:

   /*
- BLEAGHH!! This is an evil and nasty hack, made worse by the fact that
- we have to support two versions of Volume_io for it to work!  (At
- least this is done by the VOXEL_DATA hack^H^H^H^Hmacro, in <config.h>.)
- -GPW 96/04/34
  */

It does convert the values to bytes, but it fails to set the "real_range_set" flag to True. Thus, when the data are eventually compared to the thresholds, they are not converted back to the real values.

I believe a simple fix is to add the following line at the end of replace_volume_data_with_ubyte():

set_volume_real_range(data, min, max);

I'll make the change and create a pull request.

Cheers,
Dallas

**Comment by gdevenyi** [comment]
Fixed at https://github.com/BIC-MNI/mni_autoreg/commit/04866b691d4163aded31373eacbb1e59a360c71a ?
